### ISSUE TITLE
Could not pass event InventoryCloseEvent to AntiVillagerLag v2.1.0

### ISSUE THREAD

**Issue by Cruwzky** [RebelMythik/AntiVillagerLag#27] opened 2022-08-02 16:47 UTC
**Describe the bug**
I have no idea what triggered this event/error, it suddenly just showed up in our console.

**Server Info**
git-purpur-1726 (MC: 1.19)

**Additional context**
https://bin.bloom.host/ayanuguyem.css

**Comment by RebelMythik** [comment] 2022-08-02 16:49
Yep this is a known bug. Happens when you leave inventory of a wandering trader. Will be trying to fix this today

**Comment by D-VR** [comment] 2022-08-02 17:04
duplicate of https://github.com/RebelMythik/AntiVillagerLag/issues/23

I should have put the actual error message into the issue 

good thing is that it only pastes a error, it doesn't actually break anything

**Comment by RebelMythik** [comment] 2022-08-02 18:08
This is fixed in the new  update! https://www.spigotmc.org/resources/antivillagerlag.102949/updates

**Closed as completed by RebelMythik** 2022-08-02 18:08 UTC
